import csv
import re
import sys

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

artist_name = 0
location = 1
address = 2
city_state_zip = 3
instagram = 4
facebook = 5
website = 6
website_copy = 7

initial_text = '''<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

    <!-- generator="WordPress/6.2.2" created="2023-07-22 21:26" -->
<rss version="2.0"
    xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
    <title>COS</title>
    <link>http://localhost</link>
    <description></description>
    <pubDate>Sat, 22 Jul 2023 21:26:43 +0000</pubDate>
    <language>en-US</language>
    <wp:wxr_version>1.2</wp:wxr_version>
    <wp:base_site_url>http://localhost</wp:base_site_url>
    <wp:base_blog_url>http://localhost</wp:base_blog_url>

        <wp:author><wp:author_id>1</wp:author_id><wp:author_login><![CDATA[cos]]></wp:author_login><wp:author_email><![CDATA[dtpjoseph@gmail.com]]></wp:author_email><wp:author_display_name><![CDATA[cos]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>


    <generator>https://wordpress.org/?v=6.2.2</generator>
'''

ending_text = '''                </channel>
</rss>


'''


page_template = '''
        <item>
        <title><![CDATA[DOM_ARTIST_NAME]]></title>
        <link>http://localhost/DOM_HYPHENATED_LOWERCASE_ARTIST_NAME/</link>
        <pubDate>Thu, 20 Jul 2023 03:01:50 +0000</pubDate>
        <dc:creator><![CDATA[cos]]></dc:creator>
        <guid isPermaLink="false">http://localhost/?page_id=DOM_PAGE_ID</guid>
        <description></description>
        <content:encoded><![CDATA[<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">DOM_ARTIST_NAME</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>DOM_ARTIST_DESCRIPTION</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":4} -->
<h4 class="wp-block-heading"><a href="DOM_WEBSITE_URL">DOM_WEBSITE_STRING</a></h4>
<!-- /wp:heading -->

<!-- wp:heading {"level":4} -->
<h4 class="wp-block-heading">See DOM_ARTIST_NAME's work at DOM_LOCATION_NAME, DOM_LOCATION_ADDRESS</h4>
<!-- /wp:heading -->]]></content:encoded>
        <excerpt:encoded><![CDATA[]]></excerpt:encoded>
        <wp:post_id>DOM_PAGE_ID</wp:post_id>
        <wp:post_date><![CDATA[2023-07-20 03:01:50]]></wp:post_date>
        <wp:post_date_gmt><![CDATA[2023-07-20 03:01:50]]></wp:post_date_gmt>
        <wp:post_modified><![CDATA[2023-07-22 21:24:35]]></wp:post_modified>
        <wp:post_modified_gmt><![CDATA[2023-07-22 21:24:35]]></wp:post_modified_gmt>
        <wp:comment_status><![CDATA[closed]]></wp:comment_status>
        <wp:ping_status><![CDATA[open]]></wp:ping_status>
        <wp:post_name><![CDATA[DOM_HYPHENATED_LOWERCASE_ARTIST_NAME]]></wp:post_name>
        <wp:status><![CDATA[publish]]></wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:menu_order>0</wp:menu_order>
        <wp:post_type><![CDATA[page]]></wp:post_type>
        <wp:post_password><![CDATA[]]></wp:post_password>
        <wp:is_sticky>0</wp:is_sticky>
                                                        <wp:postmeta>
        <wp:meta_key><![CDATA[_wp_page_template]]></wp:meta_key>
        <wp:meta_value><![CDATA[default]]></wp:meta_value>
        </wp:postmeta>
        </item>'''


print(initial_text)

with open('2023-artists.csv', newline='') as csvfile:
    artistreader = csv.reader(csvfile, delimiter=',', quotechar='"')
    current_page = 4

    for row in artistreader:
        DOM_ARTIST_DESCRIPTION = row[website_copy]
        DOM_ARTIST_NAME = row[artist_name]
        DOM_HYPHENATED_LOWERCASE_ARTIST_NAME = row[artist_name].lower().replace(" ", "-")

        DOM_LOCATION_ADDRESS = row[address]
        if not re.search("\\.$", row[address]):
            DOM_LOCATION_ADDRESS = f'{row[address]}.'

        DOM_LOCATION_NAME = row[location]
        DOM_PAGE_ID = current_page
        current_page += 1

        DOM_WEBSITE_URL = ""
        DOM_WEBSITE_STRING = ""
        if row[website] != "":
            DOM_WEBSITE_STRING = row[website]

            if not re.search("^http://", row[website]) and not re.search("^https://", row[website]):
                DOM_WEBSITE_URL = f'https://{row[website]}'
            else:
                DOM_WEBSITE_URL = row[website]

        elif row[instagram] != "":
            handle = row[instagram].split("/")[-1].replace("@", "")
            DOM_WEBSITE_STRING = f'@{handle}'
            DOM_WEBSITE_URL = f'https://instagram.com/{handle}'

        DOM_PAGE_CONTENT = page_template

        DOM_PAGE_CONTENT = DOM_PAGE_CONTENT.replace("DOM_ARTIST_DESCRIPTION", DOM_ARTIST_DESCRIPTION)
        DOM_PAGE_CONTENT = DOM_PAGE_CONTENT.replace("DOM_ARTIST_NAME", DOM_ARTIST_NAME)
        DOM_PAGE_CONTENT = DOM_PAGE_CONTENT.replace("DOM_HYPHENATED_LOWERCASE_ARTIST_NAME", DOM_HYPHENATED_LOWERCASE_ARTIST_NAME)
        DOM_PAGE_CONTENT = DOM_PAGE_CONTENT.replace("DOM_LOCATION_ADDRESS", DOM_LOCATION_ADDRESS)
        DOM_PAGE_CONTENT = DOM_PAGE_CONTENT.replace("DOM_LOCATION_NAME", DOM_LOCATION_NAME)
        DOM_PAGE_CONTENT = DOM_PAGE_CONTENT.replace("DOM_PAGE_ID", f'{DOM_PAGE_ID}')
        DOM_PAGE_CONTENT = DOM_PAGE_CONTENT.replace("DOM_WEBSITE_URL", DOM_WEBSITE_URL)
        DOM_PAGE_CONTENT = DOM_PAGE_CONTENT.replace("DOM_WEBSITE_STRING", DOM_WEBSITE_STRING)

        print(DOM_PAGE_CONTENT)

print(ending_text)
